# Generated by Django 4.0.6 on 2022-09-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solditems',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
